### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by lilith** [jmp75/dynamic-interop-dll#1]
Hi, I noticed your library (which is [much better than my current hack](https://github.com/imazen/libwebp-net/blob/master/Imazen.WebP/Extern/LoadLibrary.cs)), and I had a few questions.
1. Would you be interested in collaborating on solving the native dependency problem? My [current scope may be over-ambitious](https://github.com/imazen/Imazen.NativeDependencyManager), but I'm sticking to granular components to prevent that from reducing its utility for simple scenarios. I've completed cross-platform assembly parsing, which was one of the more challenging components. Your implementation of xplat library loading is great, and if possible I'd like to integrate it.
2. This genre of library makes it an ILMerge candidate, but the LGPL licensing would make that impossible if the target was Ms-PL (or even Apache, since LGPL < v3). Would MIT licensing be an option? NativeDependencyManager is currently Apache 2, but I would be happy to dual-license under MIT to make it easier for you to consume, in the chance it becomes useful down the line.

**Comment by jmp75** [comment]
Hi Nathanael,

First I apologize for a belated reply, it has been a couple of fairly hectic weeks for me. I wanted to have a closer look at your work before replying. I have yet to do this, but I do not see any issue with modifying the license so that we can collaborate.

**Comment by lilith** [comment]
Thanks!

**Comment by jmp75** [comment]
Changed to MIT license as of 0.7.4
